language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov

  
sudo: required

addons:
  apt:
    packages:
    - openvpn



script:
  - python ./TestCases/Dictio.py
  - coverage run ./TestCases/BaseTestClass.py
after_success:
  - codecov

  
