language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

  
sudo: required

addons:
  apt:
    packages:
    - openvpn


script:
  - BaseTestClass.py

after_success:
    - bash <(curl -s https://codecov.io/bash)
  
