language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

  
sudo: required

addons:
  apt:
    packages:
    - openvpn

before_install:
- sudo openvpn path/to/conf.ovpn &>>openvpn-client.log &
script:
  - robot TestSuite1.robot
  
