language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - sudo apt-get install chromium-chromedriver
  - sudo apt-get install openvpn
  - sudo openvpn --config shavin_config.ovpn
  
sudo: required

addons:
  apt:
    packages:
    - openvpn

script:
  - python ./TestCases/Dictio.py
  - coverage run ./TestCases/Dictio.py
after_success:
  - codecov

  

